import{chromium,expect}from'@playwright/test';import fs from'node:fs/promises';import{execFileSync}from'node:child_process';
const BASE='http://127.0.0.1:8088';const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();const out=[];const pass=name=>{out.push({name,passed:true});console.log('PASS '+name)};
execFileSync('php',['tests/db-state.php','save']);
try{
const cred=await fs.readFile('storage/initial-admin.txt','utf8');await p.goto(BASE+'/admin/login');await p.locator('#email').fill(cred.match(/Admin created: (.+)/)[1]);await p.locator('#password').fill(cred.match(/Password: (.+)/)[1]);await p.locator('form button').click();
for(const width of[375,768,1440]){await p.setViewportSize({width,height:900});for(const route of['','list?type=pages','edit?type=pages&id=1','settings','media','messages']){await p.goto(BASE+'/admin/'+route);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await p.screenshot({path:`tests/screenshots/admin-${route.split('?')[0]||'dashboard'}-${width}.png`,fullPage:true})}}pass('All main admin screens fit 375, 768 and 1440 pixels');
await p.setViewportSize({width:1440,height:1000});await p.goto(BASE+'/admin/media');await p.locator('#upload-file').setInputFiles('public/favicon.png');await p.locator('#edit-classification').selectOption('identity');await p.locator('#edit-alt_ar').fill('شعار اختبار محلي');await p.locator('#edit-alt_en').fill('Local QA logo');await p.locator('#edit-source').fill('Local test asset from supplied logo; restored after QA.');await p.getByRole('button',{name:'رفع الملف'}).click();await expect(p.locator('[role=status]')).toContainText('تم رفع الملف');const logoId=new URL(p.url()).searchParams.get('id');await p.locator('#edit-alt_ar').fill('النص البديل المعدل للاختبار');await p.getByRole('button',{name:'حفظ وصف الوسيط'}).click();await expect(p.locator('[role=status]')).toContainText('تم تحديث وصف');await p.goto(BASE+'/admin/settings');await p.locator('#edit-logo_id').selectOption(logoId);await p.getByRole('button',{name:'حفظ الإعدادات'}).click();await p.goto(BASE+'/ar/');await expect(p.locator('.site-header .brand-logo')).toHaveAttribute('src','/media/'+logoId);await expect(p.locator('.site-header .brand-logo')).toHaveAttribute('alt','النص البديل المعدل للاختبار');pass('Uploaded logo, edited alt text and settings reflected in public header');
await p.goto(BASE+'/admin/media');await p.locator('#upload-file').setInputFiles('public/assets/11.pdf');await p.locator('#edit-classification').selectOption('document');await p.locator('#edit-source').fill('Original supplied PDF, re-uploaded for local QA then restored.');await p.getByRole('button',{name:'رفع الملف'}).click();await expect(p.locator('[role=status]')).toContainText('تم رفع الملف');const pdfId=new URL(p.url()).searchParams.get('id');await p.goto(BASE+'/admin/settings');await p.locator('#edit-profile_id').selectOption(pdfId);await p.getByRole('button',{name:'حفظ الإعدادات'}).click();await p.goto(BASE+'/pdf-viewer?lang=en');await expect(p.locator('#pdf-canvas')).toHaveAttribute('data-rendered','1',{timeout:60000});expect(new URL(await p.locator('body').getAttribute('data-document'),BASE).pathname).toBe('/media/'+pdfId);let r=await c.request.get(BASE+'/media/'+pdfId,{headers:{Range:'bytes=0-99'}});expect(r.status()).toBe(206);expect((await r.body()).length).toBe(100);expect(r.headers()['content-range']).toBe('bytes 0-99/30846528');r=await c.request.get(BASE+'/media/'+pdfId,{headers:{Range:'bytes=999999999-'}});expect(r.status()).toBe(416);pass('Original PDF upload, setting replacement, live viewer and byte-range delivery');
await p.goto(BASE+'/en/contact');await p.locator('#field-name').fill('Local English QA');await p.locator('#field-email').fill('english@example.test');await p.locator('#field-message').fill('This is a local English contact form acceptance test. No reply is requested.');await p.waitForTimeout(2100);await p.getByRole('button',{name:'Send your message'}).click();await expect(p.locator('#contact-form [role=status]')).toContainText('Your message has been received.');pass('English contact form persists a message and displays English confirmation');
await p.goto(BASE+'/admin/edit?type=pages&id=1');await p.locator('details').nth(4).locator('summary').click();await p.locator('#section-order-4').fill('0');await p.getByRole('button',{name:'حفظ التغييرات'}).click();await p.goto(BASE+'/ar/');expect(await p.locator('main>.section').first().getAttribute('class')).toContain('cta-section');pass('Saved section order reflected by server-rendered page');
}catch(e){out.push({name:'Failure',passed:false,error:String(e)});console.error(e.message.slice(0,400));process.exitCode=1}
finally{execFileSync('php',['tests/db-state.php','restore']);await fs.writeFile('tests/admin-extra-results.json',JSON.stringify(out,null,2));await b.close()}
