import {chromium,expect} from '@playwright/test';
import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
if(!process.env.TEST_URL||!process.env.ARD_CONFIG||!process.env.TEST_ADMIN_CREDENTIALS)throw new Error('Run php tests/isolated-browser.php to protect existing site content and messages.');
const BASE=process.env.TEST_URL;
const results=[];function pass(name){results.push({name,passed:true});console.log('PASS '+name)}
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
execFileSync('php',['tests/db-state.php','save']);
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();
 for(const route of ['/admin','/admin/settings','/admin/messages','/admin/media','/admin/edit?type=pages&id=1']){const r=await context.request.get(BASE+route,{maxRedirects:0});expect(r.status()).toBe(303);expect(r.headers().location).toBe('/admin/login')}pass('Administrative routes require authentication');
 let r=await context.request.post(BASE+'/ar/contact',{form:{name:'Test'}});expect(r.status()).toBe(419);pass('Contact CSRF rejection');
 await page.goto(BASE+'/ar/');expect(await page.locator('.main-nav a[href="/ar/projects"]').count()).toBe(0);expect((await context.request.get(BASE+'/ar/projects')).status()).toBe(404);pass('Unsupported project portfolio remains hidden');
 await page.locator('.sector-select').nth(2).click();await expect(page.locator('#sector-panel-2')).toBeVisible();await page.locator('.sector-select').nth(2).press('ArrowDown');await expect(page.locator('#sector-panel-3')).toBeVisible();await page.locator('.sector-select').nth(3).press('End');await expect(page.locator('#sector-panel-7')).toBeVisible();pass('Sector selection by click and keyboard');
 await page.goto(BASE+'/ar/sectors/energy');await page.locator('.language-switch a').click();expect(page.url()).toBe(BASE+'/en/sectors/energy');await expect(page.locator('html')).toHaveAttribute('dir','ltr');await page.locator('main .button').first().click();await expect(page.locator('#field-sector')).toHaveValue('energy');pass('Equivalent-page language switch and sector-prefilled contact form');
 await page.setViewportSize({width:375,height:900});await page.goto(BASE+'/ar/');await page.locator('.menu-toggle').click();await expect(page.locator('#main-nav')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.menu-toggle')).toBeFocused();await expect(page.locator('#main-nav')).toBeHidden();pass('Mobile navigation, Escape and focus');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:375,height:900}});const np=await nojs.newPage();await np.goto(BASE+'/ar/');await expect(np.locator('.sector-option a')).toHaveCount(8);await np.locator('.sector-option a[href="/ar/sectors/energy"]').click();await expect(np.locator('h1')).toHaveText('مشاريع الطاقة');await nojs.close();pass('Server-rendered navigation works without JavaScript');
 await page.goto(BASE+'/ar/profile');const iframe=page.locator('iframe');expect(await iframe.getAttribute('src')).toContain('/pdf-viewer');r=await context.request.get(new URL(await page.locator('.profile-page-hero a[download]').getAttribute('href'),BASE).href);expect(r.status()).toBe(200);expect(r.headers()['content-type']).toContain('application/pdf');const data=await r.body();expect(data.subarray(0,5).toString()).toBe('%PDF-');const profileManifest=JSON.parse(await fs.readFile('database/profile-web.json','utf8'));expect(data.length).toBe(profileManifest.web.bytes);expect(createHash('sha256').update(data).digest('hex')).toBe(profileManifest.web.sha256);pass('Optimised PDF preview source, complete download and verified checksum');
 await page.goto(BASE+'/ar/contact');await page.locator('#field-name').fill('اختبار قبول آلي');await page.locator('#field-email').fill('qa@example.test');await page.locator('#field-company').fill('QA Test');await page.locator('#field-sector').selectOption('energy');const msg='اختبار محلي لحفظ رسالة التواصل <script>alert("xss")</script> — لا يحتاج إلى متابعة فعلية.';await page.locator('#field-message').fill(msg);await page.waitForTimeout(2200);await page.locator('button[type=submit]').click();await expect(page.locator('#contact-form [role=status]')).toContainText('تم استلام رسالتك');pass('Contact message saved and receipt shown after database success');
 const saved=JSON.parse(execFileSync('php',['tests/db-state.php','messages'],{encoding:'utf8'}));expect(saved).toHaveLength(1);expect(saved[0].email_status).toBe('pending');execFileSync('php',['bin/mail-worker.php']);const delivered=JSON.parse(execFileSync('php',['tests/db-state.php','messages'],{encoding:'utf8'}));expect(delivered[0].email_status).toBe('logged');const messageId=saved[0].id;pass('Mail notification queue and local worker independently processed');
 await page.goto(BASE+'/ar/contact');await page.locator('#field-name').fill('اختبار قبول آلي');await page.locator('#field-email').fill('qa@example.test');await page.locator('#field-message').fill(msg);await page.waitForTimeout(2100);const duplicate=page.waitForResponse(res=>res.url().includes('/ar/contact')&&res.request().method()==='POST');await page.locator('button[type=submit]').click();expect((await duplicate).status()).toBe(409);pass('Duplicate enquiry rejected');
 await page.goto(BASE+'/ar/contact');let csrf=await page.locator('[name=csrf]').inputValue();await page.waitForTimeout(2100);r=await context.request.post(BASE+'/ar/contact',{form:{csrf,name:'A',email:'invalid',message:'short',sector:'invented'}});expect(r.status()).toBe(422);pass('Server validates required fields, email, length and sector');
 await page.goto(BASE+'/admin/login');const credentials=await fs.readFile(process.env.TEST_ADMIN_CREDENTIALS,'utf8');const email=credentials.match(/Admin created: (.+)/)[1];const password=credentials.match(/Password: (.+)/)[1];await page.locator('#email').fill(email);await page.locator('#password').fill(password);await page.locator('form button').click();await expect(page.locator('h1')).toContainText('مرحباً');pass('Hashed-password login and protected dashboard');
 await page.goto(BASE+'/admin/message?id='+messageId);await expect(page.locator('.admin-message')).toHaveText(msg);expect(await page.locator('.admin-message script').count()).toBe(0);await page.locator('#message-status').selectOption('in_progress');await page.getByRole('button',{name:'تحديث الحالة'}).click();await expect(page.locator('#message-status')).toHaveValue('in_progress');pass('Admin inbox escapes user HTML and persists message status');
 await page.goto(BASE+'/admin/edit?type=pages&id=1');await expect(page.locator('h1')).toContainText('تحرير');await page.locator('#edit-title').fill('عنوان مراجعة محلي\nمتصل بقاعدة البيانات.');await page.locator('details').first().locator('summary').click();await page.locator('#section-visible-0').selectOption('0');await page.getByRole('button',{name:'حفظ التغييرات'}).click();await expect(page.locator('[role=status]')).toContainText('تم حفظ المحتوى');await page.goto(BASE+'/ar/');await expect(page.locator('h1')).toContainText('عنوان مراجعة محلي');expect(await page.locator('.intro-section').count()).toBe(0);pass('CMS text changes and section visibility reach public page');
 await page.goto(BASE+'/admin/edit?type=pages&id=1&locale=en');await page.locator('#edit-title').fill('QA translation update');await page.locator('#edit-approval').selectOption('approved');await page.getByRole('button',{name:'حفظ التغييرات'}).click();await page.goto(BASE+'/en/');await expect(page.locator('h1')).toHaveText('QA translation update');pass('Separate English translation and approval management');
 await page.goto(BASE+'/admin/edit?type=sectors&id=6');await page.locator('#edit-status').selectOption('draft');await page.getByRole('button',{name:'حفظ التغييرات'}).click();expect((await context.request.get(BASE+'/ar/sectors/energy')).status()).toBe(404);await page.goto(BASE+'/ar/sectors/energy?preview=1');await expect(page.locator('.preview-bar')).toBeVisible();pass('Draft hiding and authenticated content preview');
 await page.goto(BASE+'/admin/settings');await page.locator('#edit-phone').fill('+964 780 144 4553');await page.getByRole('button',{name:'حفظ الإعدادات'}).click();await expect(page.locator('[role=status]')).toContainText('تم تحديث');await page.goto(BASE+'/ar/contact');await expect(page.locator('.contact-detail a[href="tel:+9647801444553"]')).toBeVisible();pass('Official settings updates render in contact page');
 await page.goto(BASE+'/admin/media');await page.locator('#upload-file').setInputFiles({name:'test.php',mimeType:'application/x-php',buffer:Buffer.from('<?php echo "unsafe";')});await page.locator('#edit-source').fill('Local upload rejection test');await page.getByRole('button',{name:'رفع الملف'}).click();await expect(page.locator('[role=alert]')).toContainText('الأنواع المقبولة');pass('Executable upload rejected');
 await page.locator('#upload-file').setInputFiles('public/favicon.png');await page.locator('#edit-classification').selectOption('project');await page.locator('#edit-alt_ar').fill('صورة اختبار محلية');await page.locator('#edit-alt_en').fill('Local test image');await page.locator('#edit-source').fill('Synthetic local QA fixture; not an actual company project.');await page.getByRole('button',{name:'رفع الملف'}).click();await expect(page.locator('[role=status]')).toContainText('تم رفع الملف');const uploadedId=new URL(page.url()).searchParams.get('id');const anon=await browser.newContext();expect((await anon.request.get(BASE+'/media/'+uploadedId)).status()).toBe(404);pass('Validated image upload and private unused media');
 await page.goto(BASE+'/admin/edit?type=projects');await page.locator('#edit-slug').fill('qa-project');await page.locator('#edit-title').fill('مشروع اختبار محلي غير حقيقي');await page.locator('#edit-summary').fill('سجل اختبار مؤقت للتحقق من وظائف إدارة المشاريع.');await page.locator('#edit-source_ref').fill('Synthetic QA only, removed after verification.');await page.locator('#edit-sector_id').selectOption('1');await page.locator('#edit-image_id').selectOption(uploadedId);await page.locator('#edit-services').fill('نطاق اختبار محلي');await page.getByRole('button',{name:'حفظ التغييرات'}).click();await expect(page.locator('[role=status]')).toContainText('تم حفظ المحتوى');const projectId=new URL(page.url()).searchParams.get('id');expect((await anon.request.get(BASE+'/ar/projects/qa-project')).status()).toBe(404);pass('New project draft remains private');
 await page.locator('#edit-status').selectOption('published');await page.locator('#edit-translation_status').selectOption('published');await page.locator('#edit-approval').selectOption('approved');await page.getByRole('button',{name:'حفظ التغييرات'}).click();await page.goto(BASE+'/ar/projects?sector=general-contracting');await expect(page.locator('.project-grid h3')).toContainText('مشروع اختبار');await page.locator('.project-grid a').click();await expect(page.locator('h1')).toHaveText('مشروع اختبار محلي غير حقيقي');expect((await anon.request.get(BASE+'/media/'+uploadedId)).status()).toBe(200);pass('Approved project publication, sector filter, details and linked media');
 await page.goto(BASE+'/admin/settings');csrf=await page.locator('[name=csrf]').first().inputValue();r=await context.request.post(BASE+'/admin/settings',{form:{action:'save-settings',csrf:'invalid'}});expect(r.status()).toBe(419);pass('Admin mutation CSRF rejection');
 await page.goto(BASE+'/admin/message?id='+messageId);await page.locator('[name=confirm]').check();await page.getByRole('button',{name:'حذف الرسالة',exact:true}).click();expect(JSON.parse(execFileSync('php',['tests/db-state.php','messages'],{encoding:'utf8'}))).toHaveLength(0);pass('Explicit message deletion persists');
 await page.goto(BASE+'/admin');await page.getByRole('button',{name:'خروج',exact:true}).click();expect(page.url()).toBe(BASE+'/admin/login');expect((await context.request.get(BASE+'/admin',{maxRedirects:0})).status()).toBe(303);pass('Logout invalidates authenticated access');
 // Login rate limiting uses atomic database counters and does not depend on client JavaScript.
 for(let i=0;i<6;i++){await page.goto(BASE+'/admin/login');csrf=await page.locator('[name=csrf]').inputValue();r=await context.request.post(BASE+'/admin/login',{form:{csrf,email:'rate-test@example.test',password:"' OR 1=1 --"}})}expect(r.status()).toBe(429);pass('Login throttling and SQL-injection-style credentials rejected');
 await anon.close();await context.close();
}catch(e){results.push({name:'Failure',passed:false,error:String(e)});console.error(e);process.exitCode=1}
finally{execFileSync('php',['tests/db-state.php','restore']);await fs.writeFile('tests/functional-results.json',JSON.stringify(results,null,2));await browser.close()}
