import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';import {execFileSync} from 'node:child_process';
const BASE='http://127.0.0.1:8088',results=[];const pass=name=>{results.push({name,passed:true});console.log('PASS '+name)};
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});let snapshot=false;
try{
 const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(BASE+'/ar/',{waitUntil:'networkidle'});const video=p.locator('[data-showcase-video]');const toggle=p.locator('[data-video-toggle]');
 await expect(p.locator('[data-slide]')).toHaveCount(4);await expect(video).toHaveJSProperty('paused',false);await expect(video).toHaveJSProperty('muted',true);await expect(video).toHaveAttribute('playsinline','');await expect(p.locator('[data-video-pause-icon]')).toBeVisible();await expect(p.locator('[data-video-play-icon]')).toBeHidden();await expect(toggle).toHaveAttribute('aria-label','إيقاف الفيديو مؤقتاً');
 expect(await video.evaluate(v=>v.videoWidth)).toBe(1280);expect(await video.evaluate(v=>v.currentTime)).toBeGreaterThan(0);pass('First home slide plays silently and inline at 720p, with correct pause icon and accessible label');
 await toggle.click();await expect(video).toHaveJSProperty('paused',true);const stopped=await video.evaluate(v=>v.currentTime);await p.waitForTimeout(250);expect(await video.evaluate(v=>v.currentTime)).toBe(stopped);await expect(p.locator('[data-video-play-icon]')).toBeVisible();await expect(toggle).toHaveAttribute('aria-label','تشغيل الفيديو');
 await p.locator('[data-slide-to="1"]').click();await p.locator('[data-slide-to="0"]').click();await expect(video).toHaveJSProperty('paused',true);await toggle.click();await expect(video).toHaveJSProperty('paused',false);pass('Pause/play works and a manual pause survives changing slides');
 await p.locator('[data-slide-to="2"]').click();await expect(video).toHaveJSProperty('paused',true);await p.locator('[data-slide-to="0"]').click();await expect(video).toHaveJSProperty('paused',false);await p.locator('.site-footer').scrollIntoViewIfNeeded();await expect(video).toHaveJSProperty('paused',true);await video.scrollIntoViewIfNeeded();await expect(video).toHaveJSProperty('paused',false);pass('Playback stops on inactive slides and offscreen, and resumes only when visible');
 await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});await expect(video).toHaveJSProperty('paused',true);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))});await expect(video).toHaveJSProperty('paused',false);pass('Document visibility handler pauses background playback');
 const desktop=new URL(await video.getAttribute('data-video-desktop'),BASE);const mobile=new URL(await video.getAttribute('data-video-mobile'),BASE);let response=await c.request.get(desktop.href,{headers:{Range:'bytes=0-4095'}});expect(response.status()).toBe(206);expect(response.headers()['content-range']).toMatch(/^bytes 0-4095\//);expect((await response.body()).length).toBe(4096);expect(response.headers()['content-type']).toBe('video/mp4');expect((await response.body()).indexOf(Buffer.from('moov'))).toBeLessThan(128);response=await c.request.get(desktop.href,{headers:{Range:'bytes=9999999-'}});expect(response.status()).toBe(416);response=await c.request.head(mobile.href);expect(+response.headers()['content-length']).toBeLessThan(350000);pass('HTTP 206 byte ranges, faststart metadata, invalid-range 416 and small mobile payload');
 const reduced=await b.newContext({viewport:{width:375,height:900},reducedMotion:'reduce'});const rp=await reduced.newPage();const requests=[];rp.on('request',r=>{if([desktop.pathname,mobile.pathname].includes(new URL(r.url()).pathname))requests.push(r.url())});await rp.goto(BASE+'/en/',{waitUntil:'networkidle'});await rp.locator('[data-showcase-video]').scrollIntoViewIfNeeded();expect(await rp.locator('video').getAttribute('src')).toBeNull();expect(requests).toHaveLength(0);await expect(rp.locator('.showcase-video-poster')).toBeVisible();await rp.locator('[data-video-toggle]').click();await expect(rp.locator('video')).toHaveJSProperty('paused',false);await expect(rp.locator('video')).toHaveJSProperty('videoWidth',854);expect(requests.length).toBeGreaterThan(0);expect(requests.every(url=>new URL(url).pathname===mobile.pathname)).toBe(true);pass('Reduced-motion preference downloads no video until Play; mobile fetches only the 480p variant');await reduced.close();
 const saver=await b.newContext({viewport:{width:1440,height:1000}});await saver.addInitScript(()=>{Object.defineProperty(navigator,'connection',{get:()=>({saveData:true,effectiveType:'2g',addEventListener(){}})})});const sp=await saver.newPage();await sp.goto(BASE+'/ar/',{waitUntil:'networkidle'});expect(await sp.locator('video').getAttribute('src')).toBeNull();await sp.locator('[data-video-toggle]').click();await expect(sp.locator('video')).toHaveJSProperty('paused',false);await expect(sp.locator('video')).toHaveJSProperty('videoWidth',854);pass('Save-Data / slow connection leaves poster until user requests the smaller video');await saver.close();
 const blocked=await b.newContext({viewport:{width:1440,height:1000}});await blocked.addInitScript(()=>{HTMLMediaElement.prototype.play=function(){return Promise.reject(new DOMException('Blocked by test policy','NotAllowedError'))}});const bp=await blocked.newPage();await bp.goto(BASE+'/ar/',{waitUntil:'networkidle'});await expect(bp.locator('.showcase-video-poster')).toBeVisible();await expect(bp.locator('[data-video-toggle]')).toHaveAttribute('aria-label','تشغيل الفيديو');await expect(bp.locator('[data-video-error]')).toBeHidden();pass('Browser autoplay rejection keeps a usable poster and Play control');await blocked.close();
 const offline=await b.newContext({viewport:{width:1440,height:1000}});const op=await offline.newPage();await op.route('**/media/*',route=>route.abort());await op.goto(BASE+'/ar/');await expect(op.locator('[data-video-error]')).toBeVisible();await expect(op.locator('.showcase-video-poster')).toBeVisible();await expect(op.locator('[data-video-toggle]')).toBeHidden();pass('Failed video request preserves poster and offers a direct alternative');await offline.close();
 const nojs=await b.newContext({javaScriptEnabled:false,viewport:{width:375,height:900}});const np=await nojs.newPage();await np.goto(BASE+'/ar/');await expect(np.locator('.showcase-film-fallback')).toBeVisible();const href=await np.locator('.showcase-film-fallback').getAttribute('href');const fallback=await nojs.request.get(new URL(href,BASE).href);expect(fallback.status()).toBe(200);expect(await fallback.text()).toContain('controls preload="metadata"');pass('No-JavaScript fallback opens a native video player page');await nojs.close();
 for(const width of [375,768,1440])for(const lang of ['ar','en']){await p.setViewportSize({width,height:1000});await p.emulateMedia({reducedMotion:'reduce'});await p.goto(`${BASE}/${lang}/`);await expect(p.locator('[data-showcase-video]')).toHaveCount(1);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const dimensions=await p.locator('.showcase-video-screen').evaluate(el=>{const r=el.getBoundingClientRect();return r.width/r.height});expect(Math.abs(dimensions-16/9)).toBeLessThan(.01);await expect(p.locator('[data-slide]')).toHaveCount(4)}pass('Whole 16:9 composition retained in both languages at 375, 768 and 1440 pixels');
 expect(errors).toEqual([]);pass('No application JavaScript errors');
 // Admin checks retain the user's current data and restore it after the test.
 execFileSync('php',['tests/db-state.php','save']);snapshot=true;await p.goto(BASE+'/admin/login');const auth=await fs.readFile('storage/initial-admin.txt','utf8');await p.locator('#email').fill(auth.match(/Admin created: (.+)/)[1]);await p.locator('#password').fill(auth.match(/Password: (.+)/)[1]);await p.locator('form button').click();await expect(p.locator('h1')).toContainText('مرحباً');
 const vid=desktop.pathname.split('/').at(-1),mid=mobile.pathname.split('/').at(-1);const anon=await b.newContext();const ap=await anon.newPage();await p.goto(BASE+'/admin/settings');await p.locator('#edit-home_video_id').selectOption('');await p.getByRole('button',{name:'حفظ الإعدادات'}).click();await ap.goto(BASE+'/ar/');await expect(ap.locator('video')).toHaveCount(0);expect((await anon.request.get(desktop.href)).status()).toBe(404);expect((await anon.request.get(mobile.href)).status()).toBe(404);pass('Home video setting persists and removes the film; unreferenced media endpoints are unavailable');
 const aboutId=execFileSync('php',['-r',`require 'app/bootstrap.php';echo record('pages','about')['id'];`],{encoding:'utf8'});await p.goto(`${BASE}/admin/edit?type=pages&id=${aboutId}`);await p.locator('#slide-title-0').evaluate(el=>el.closest('details').open=true);await p.locator('#slide-title-0').fill('فيديو مراجعة محلي');await p.locator('#slide-video-0').selectOption(vid);await p.getByRole('button',{name:'حفظ التغييرات'}).click();await expect(p.locator('[role=status]')).toContainText('تم حفظ المحتوى');await ap.goto(BASE+'/ar/about');await expect(ap.locator('video')).toHaveCount(0);expect((await anon.request.get(desktop.href)).status()).toBe(404);await p.goto(BASE+'/ar/about?preview=1');await expect(p.locator('video')).toHaveCount(1);pass('Draft video slide stays private, automatically receives its poster and is available in authenticated preview');
 await p.goto(`${BASE}/admin/edit?type=pages&id=${aboutId}`);await p.locator('#slide-status-0').evaluate(el=>el.closest('details').open=true);await p.locator('#slide-status-0').selectOption('published');await p.getByRole('button',{name:'حفظ التغييرات'}).click();await ap.goto(BASE+'/ar/about');await expect(ap.locator('video')).toHaveCount(1);expect((await anon.request.get(mobile.href,{headers:{Range:'bytes=0-63'}})).status()).toBe(206);pass('Published custom video slide and its mobile variant work from CMS');
 await p.goto(`${BASE}/admin/edit?type=pages&id=${aboutId}`);const form=await p.locator('.admin-editor').evaluate(el=>Object.fromEntries(new FormData(el).entries()));form['slider[0][video_id]']='10';response=await c.request.post(p.url(),{form});expect(response.status()).toBe(422);expect(await response.text()).toContain('اختر فيديو معداً للويب');pass('Server rejects PDF/image IDs in the video field');
 const manifest=JSON.parse(await fs.readFile('database/video-seed.json','utf8'));expect((await c.request.get(BASE+manifest.assets.desktop.path)).status()).toBe(404);pass('Local router prevents bypassing media access through a direct video asset path');
 await anon.close();await c.close();
}catch(e){console.error(e);results.push({name:'Failure',passed:false,error:String(e)});process.exitCode=1}
finally{if(snapshot)execFileSync('php',['tests/db-state.php','restore']);await b.close();await fs.writeFile('tests/video-results.json',JSON.stringify(results,null,2))}
