import json
from pathlib import Path
ar_name='شركة ارض اليرموك للمقاولات العامة و التجارة العامة وتكنولوجيا المعلومات والخدمات العامة والاتصالات ومشاريع الطاقة و الحلول البرمجية الرقمية والذكية والاستثمارات الصناعية محدودة المسؤولية'
en_name='ARD ALYARMWK CO. For general contracting, general trading, information technology, public services, communications, energy projects, digital and smart software solutions, and industrial investments LTD.'
def section(key,title,text='',items=[],order=0):return dict(key=key,title=title,text=text,items=items,order=order,visible=True)
def tr(title,summary,body,ref,lang):return dict(title=title,summary=summary,body=body,seo_title=title,seo_description=summary[:300],source_ref=ref,approval='approved' if lang=='ar' else 'review',status='published')
def item(kind,slug,ar,en,image,order):return dict(kind=kind,slug=slug,translations=dict(ar=ar,en=en),image=image,sort_order=order,status='published')
items=[]
sectors=[
('general-contracting','المقاولات العامة','General contracting','من الفكرة إلى البناء.','From plans to places.',
'أعمال البناء والتشييد وتطوير البنى التحتية، ضمن نطاق يجمع التنفيذ والإشراف الهندسي ومشاريع الإعمار.','Construction and infrastructure development, encompassing project delivery, engineering supervision and reconstruction.',
['تنفيذ مشاريع البناء والتشييد','تطوير البنى التحتية','إنشاء المجمعات السكنية والتجارية والصناعية','الإشراف الهندسي وتنفيذ مشاريع الإعمار'],['Building and construction projects','Infrastructure development','Residential, commercial and industrial complexes','Engineering supervision and reconstruction'],6,'architecture'),
('general-trading','التجارة العامة','General trading','تجهيز يدعم استمرارية الأعمال.','Supply that supports business.',
'توفير المواد والمستلزمات والتجهيزات المتخصصة لتلبية احتياجات الجهات الحكومية والخاصة.','Materials, supplies and specialist equipment for the needs of public and private sector organisations.',
['توفير المواد الأولية والمستلزمات الإنشائية','التجهيزات الكهربائية والميكانيكية','توريد المعدات التخصصية','تلبية احتياجات القطاعات الحكومية والخاصة'],['Raw materials and construction supplies','Electrical and mechanical equipment','Specialist equipment procurement','Supply for public and private sectors'],6,'trade'),
('information-technology','تكنولوجيا المعلومات','Information technology','بنية رقمية للأعمال المتطورة.','Digital foundations for business.',
'حلول للبنى التحتية الرقمية والأنظمة المؤسسية، تدعم إنشاء الشبكات ومراكز البيانات والحوسبة السحابية والتحول الرقمي.','Digital infrastructure and enterprise systems covering networks, data centres, cloud computing and digital transformation.',
['إنشاء الشبكات والأنظمة','البنى التحتية الرقمية ومراكز البيانات','الأنظمة المؤسسية ERP وCRM','خدمات الحوسبة السحابية والتحول الرقمي'],['Networks and systems','Digital infrastructure and data centres','Enterprise systems: ERP and CRM','Cloud computing and digital transformation'],6,'it'),
('general-services','الخدمات العامة','General services','دعم تشغيلي يرافق أعمالكم.','Operational support for your work.',
'خدمات تشغيلية ولوجستية مساندة تشمل التوريد والتجهيز وإدارة المواقع ودعم العمليات الميدانية.','Operational and logistical support including supply, site management and field operations.',
['خدمات التوريد والتجهيز','إدارة وتشغيل المواقع','خدمات الدعم الفني','دعم العمليات الميدانية'],['Supply and provisioning','Site management and operation','Technical support services','Field operations support'],7,'team'),
('communications','الاتصالات','Communications','روابط تصل المواقع والأعمال.','Connecting sites and operations.',
'مشاريع اتصالات وتقنيات ربط للمواقع، تشمل شبكات الألياف الضوئية والأنظمة اللاسلكية وأنظمة المراقبة الأمنية.','Communications and site connectivity, covering fibre optic networks, wireless communications and security surveillance systems.',
['تنفيذ مشاريع الاتصالات','شبكات الألياف الضوئية','أنظمة المراقبة الأمنية','أنظمة الاتصالات اللاسلكية وحلول الربط بين المواقع'],['Communications projects','Fibre optic networks','Security surveillance systems','Wireless communications and inter-site connectivity'],7,'software'),
('energy','مشاريع الطاقة','Energy projects','الطاقة اليوم. وآفاق الغد.','Energy today. Possibilities ahead.',
'أنشطة في الطاقة التقليدية والمتجددة، من مشاريع الطاقة الشمسية وأعمال الكهرباء إلى إدارة الطاقة وتشغيل المحطات.','Conventional and renewable energy activities, from solar projects and electrical works to energy management and plant operation.',
['تجهيز وتنفيذ مشاريع الطاقة الشمسية','أنظمة إدارة الطاقة للمؤسسات','أعمال الكهرباء والقدرة','صيانة وتشغيل محطات الطاقة'],['Supply and implementation of solar energy projects','Energy management systems for organisations','Electrical and power works','Power plant maintenance and operation'],7,'energy'),
('digital-solutions','الحلول البرمجية الرقمية والذكية','Digital & smart software solutions','برمجيات تستجيب لاحتياجات الأعمال.','Software shaped around business.',
'تطوير التطبيقات والأنظمة المتخصصة، مع حلول ذكية تدعم العمليات المالية واللوجستية والتحليل المتقدم.','Specialist applications and systems, with smart solutions supporting financial operations, logistics and advanced analytics.',
['التطبيقات الذكية','الأنظمة المالية والمصرفية','أنظمة التشغيل اللوجستي','حلول الذكاء الاصطناعي والتحليل المتقدم'],['Smart applications','Financial and banking systems','Logistics operations systems','Artificial intelligence and advanced analytics'],8,'software'),
('industrial-investments','الاستثمارات الصناعية','Industrial investments','إمكانات تتحول إلى إنتاج.','Potential into production.',
'دعم القطاع الصناعي عبر إنشاء وتجهيز خطوط الإنتاج وتوفير المعدات وتطوير المشاريع الصناعية المبتكرة.','Supporting industry through production line development, equipment supply and innovative industrial projects.',
['إنشاء وتجهيز خطوط إنتاج','شراكات صناعية وطنية','توفير المعدات والخطوط الإنتاجية','تطوير مشاريع صناعية مبتكرة'],['Production line development and setup','National industrial partnerships','Industrial equipment and production lines','Innovative industrial project development'],8,'industry')]
for i,(slug,ar,en,tag_ar,tag_en,desc_ar,desc_en,list_ar,list_en,pg,im) in enumerate(sectors):
 items.append(item('sectors',slug,tr(ar,desc_ar,{'eyebrow':tag_ar,'services':list_ar,'sections':[]},f'PDF physical page {pg}', 'ar'),tr(en,desc_en,{'eyebrow':tag_en,'services':list_en,'sections':[]},f'Proposed translation of PDF physical page {pg}', 'en'),im,i+1))
about_ar='تأسست شركة ارض اليرموك عام 2017، وتنشط في المقاولات العامة والتجارة العامة. ومع توسع أعمالها، شملت أنشطتها تكنولوجيا المعلومات والخدمات العامة والاتصالات ومشاريع الطاقة والحلول البرمجية الرقمية والذكية والاستثمارات الصناعية.\n\nتتجه الشركة إلى تلبية احتياجات السوق العراقي من خلال تنوع مجالات العمل، والتخطيط الفعال، وتطوير الكفاءات، والاستفادة من التقنيات الحديثة.'
about_en='Established in 2017, ARD ALYARMWK CO. operates in general contracting and general trading. Its activities have expanded to include information technology, general services, communications, energy projects, digital and smart software solutions, and industrial investments.\n\nThe company seeks to meet the needs of the Iraqi market through diversified activities, effective planning, skills development and modern technology.'
values_ar=[{'title':'التعلّم','text':'إثراء المعرفة وتبادل الخبرات وتحويل التحديات إلى خبرة مثمرة.'},{'title':'الريادة','text':'إنتاج المعرفة وتحويل الأفكار الجديدة إلى تطبيقات عملية.'},{'title':'الأصالة','text':'أفكار مستقلة تستند إلى معرفة راسخة ومبادئ واضحة.'},{'title':'المصداقية','text':'تقديم الخدمات والمنتجات طبقاً للمواصفات المعلنة.'},{'title':'نفع الناس','text':'تقديم خدمات مفيدة وقيمة مضافة للمجتمع وشركاء العمل.'}]
values_en=[{'title':'Learning','text':'Growing knowledge, sharing experience and learning from challenges.'},{'title':'Leadership','text':'Turning new ideas and knowledge into practical applications.'},{'title':'Originality','text':'Independent ideas grounded in knowledge and clear principles.'},{'title':'Credibility','text':'Delivering services and products to their stated specifications.'},{'title':'Serving people','text':'Useful services and added value for communities and business partners.'}]
home_ar=[section('about','جذور عراقية.\nوطموح يتّسع.', 'من المقاولات والتجارة إلى التقنية والطاقة، تجمع ارض اليرموك مجالات عمل متنوعة ضمن رؤية تسعى إلى النمو والتطوير وخدمة السوق العراقي.',order=1),section('sectors','مجالات متنوّعة.\nرؤية واحدة.','اكتشف نطاق أعمالنا، واختر المجال الذي يلتقي مع احتياجات مشروعك.',order=2),section('approach','ما يجمع أعمالنا،\nهو ما نؤمن به.', 'مبادئ توجه العمل والعلاقات، كما يوضحها الملف التعريفي للشركة.',[{'title':'التخطيط والتطوير','text':'تخطيط فعّال وتطوير مستمر للكفاءات والتقنيات.'},{'title':'الجودة والالتزام','text':'العناية بالمواصفات والدقة في التنفيذ واحترام الجداول الزمنية.'},{'title':'علاقات طويلة الأمد','text':'الشفافية والمصداقية أساس التعامل مع الجهات الحكومية والخاصة.'}],3),section('profile','تعرّف علينا\nعن قرب.','رؤيتنا، قيمنا ومجالات عملنا في ملف واحد. تصفّح الملف التعريفي الرسمي لشركة ارض اليرموك.',order=4),section('cta','لنبدأ بمحادثة.','أخبرنا عن احتياجاتك، ودعنا نناقش كيف تتصل بمجالات عملنا.',order=5)]
home_en=[section('about','Iraqi roots.\nWider horizons.','From contracting and trade to technology and energy, ARD ALYARMWK CO. brings diverse activities together with a vision for growth, development and service to the Iraqi market.',order=1),section('sectors','Diverse sectors.\nOne vision.','Explore our activities and find the sector that connects with your project.',order=2),section('approach','Shared principles.\nAcross every field.','The principles that guide our work and relationships, as set out in our company profile.',[{'title':'Planning & development','text':'Effective planning and the continuous development of skills and technology.'},{'title':'Quality & commitment','text':'Attention to specifications, precise execution and respect for schedules.'},{'title':'Lasting relationships','text':'Transparency and credibility in our relationships with public and private organisations.'}],3),section('profile','A closer look\nat our company.','Our vision, values and fields of work in one place. Explore the official ARD ALYARMWK CO. profile.',order=4),section('cta','Every project starts\nwith a conversation.','Tell us what you need and let’s discuss how it connects with our fields of work.',order=5)]
items.append(item('pages','home',tr('نبني بثقة.\nونتقدّم برؤية.','ارض اليرموك، شركة عراقية تجمع المقاولات والتجارة والتقنية والطاقة، وتتطلع إلى المساهمة في تطوير الأعمال والبنى التحتية. ',{'eyebrow':'ارض اليرموك · آفاق متعددة','sections':home_ar},'PDF pp. 2, 6–9; editorial synthesis','ar'),tr('Built on trust.\nDriven by vision.','An Iraqi company bringing together contracting, trade, technology and energy, seeking to contribute to business and infrastructure development.',{'eyebrow':'ARD ALYARMWK CO. · WIDER HORIZONS','sections':home_en},'Proposed translation; PDF pp. 2, 6–9','en'),'architecture',0))
for locale,title,summary,body,values in [('ar','جذور عراقية.\nوطموح يتّسع.','نعمل برؤية تجمع تنوّع الأنشطة مع التطوير المستمر.',about_ar,values_ar),('en','Iraqi roots.\nWider horizons.','A vision that brings diverse activities and continuous development together.',about_en,values_en)]:
 sec=[section('intro','من نحن' if locale=='ar' else 'Who we are',body,order=1),section('vision','رؤيتنا' if locale=='ar' else 'Our vision','تحقيق الريادة في أعمالنا لنكون على قمة الشركات' if locale=='ar' else 'To achieve leadership in our fields and stand among the leading companies.',order=2),section('mission','رسالتنا' if locale=='ar' else 'Our mission','مواصلة النمو والتوسع استناداً على أعلى الخبرات والكفاءات البشرية، وأفضل التقنيات الفنية والمعلوماتية، والمحافظة على معايير الجودة والسلامة العالمية، لتحقيق تطلعاتنا لمستقبل مشرق بإذن الله.' if locale=='ar' else 'To continue growing and expanding through human expertise and skills, technical and information technologies, and a commitment to international quality and safety standards, to realise our aspirations for a bright future, God willing.',order=3),section('values','قيمنا' if locale=='ar' else 'Our values','',values,4),section('goals','نحو مستقبل أكثر اتصالاً' if locale=='ar' else 'Towards a more connected future','تضع الشركة التوسع في القطاعات الحيوية داخل العراق، والاستثمار في التكنولوجيا والتحول الرقمي، وتطوير العلاقات طويلة الأمد، ضمن أهدافها الاستراتيجية.' if locale=='ar' else 'The company’s strategic objectives include expansion in vital sectors in Iraq, investment in technology and digital transformation, and the development of long-term relationships.',order=5)]
 if locale=='ar':about_ar_t=tr(title,summary,{'eyebrow':'عن ارض اليرموك','sections':sec},'PDF physical pages 2–5, 9','ar')
 else:about_en_t=tr(title,summary,{'eyebrow':'ABOUT OUR COMPANY','sections':sec},'Proposed translation; PDF physical pages 2–5, 9','en')
items.append(item('pages','about',about_ar_t,about_en_t,'team',1))
items.append(item('pages','sectors',tr('تنوّع يصنع\nفرصاً أوسع.','ثمانية مجالات عمل تشمل البناء والتجارة والتقنية والخدمات والطاقة والصناعة، لتلبية احتياجات السوق العراقي.',{'eyebrow':'مجالات أعمالنا','sections':[]},'PDF physical pages 6–8','ar'),tr('More fields.\nMore possibilities.','Eight fields of work spanning construction, trade, technology, services, energy and industry to meet the needs of the Iraqi market.',{'eyebrow':'OUR SECTORS','sections':[]},'Proposed translation; PDF physical pages 6–8','en'),'energy',2))
items.append(item('pages','profile',tr('رؤيتنا وأعمالنا.\nبين يديك.','الملف التعريفي الرسمي لشركة ارض اليرموك؛ نبذة عن الشركة ورؤيتها ورسالتها وقيمها وأنشطتها وأهدافها الاستراتيجية.',{'eyebrow':'الملف التعريفي','sections':[section('contents','داخل الملف','',[{'title':'الشركة ورؤيتها','text':'التعريف بالشركة والرؤية والرسالة.'},{'title':'القيم والأهداف','text':'المبادئ والأهداف التي توجه أعمال الشركة.'},{'title':'مجالات العمل','text':'مجالات العمل وبيانات الاتصال الرسمية.'}])]},'User-supplied original 10-page PDF','ar'),tr('Our vision and work.\nIn your hands.','The official ARD ALYARMWK CO. profile: an introduction to the company, its vision, mission, values, activities and strategic objectives.',{'eyebrow':'COMPANY PROFILE','sections':[section('contents','Inside the profile','',[{'title':'Company & vision','text':'Company introduction, vision and mission.'},{'title':'Values & objectives','text':'The principles and objectives guiding our work.'},{'title':'Fields of work','text':'Business activities and official contact details.'}])]},'Proposed translation; original PDF is Arabic with English cover','en'),'profile-cover',3))
items.append(item('pages','contact',tr('لنتحدث عن\nمشروعك القادم.','شاركنا احتياجاتك أو استفسارك، وحدد القطاع المناسب ليتسنى لنا متابعة رسالتك.',{'eyebrow':'اتصل بنا','sections':[]},'Contact PDF physical page 10; form copy editorial','ar'),tr('Let’s talk about\nyour next project.','Share your requirements or enquiry and choose a relevant sector so we can follow up on your message.',{'eyebrow':'GET IN TOUCH','sections':[]},'Proposed translation; contact PDF physical page 10','en'),None,4))
privacy_ar=[section('collection','البيانات التي نجمعها','عند استخدام نموذج التواصل، نجمع الاسم والبريد الإلكتروني والرسالة. الشركة ورقم الهاتف والقطاع حقول اختيارية. تُحفظ لغة الرسالة وتاريخ إرسالها ورقمها المرجعي وحالة متابعتها.'),section('use','كيف نستخدم بياناتك','تستخدم الشركة بيانات التواصل للرد على الاستفسارات ومتابعة طلبات الأعمال. لا تُستخدم لإرسال حملات تسويقية من هذا الموقع. يُحفظ الطلب في قاعدة البيانات قبل تأكيد استلامه. عند تفعيل إشعارات البريد، يُرسل إلى البريد الإداري رقم الطلب ورابط لوحة الإدارة دون نص الرسالة.'),section('security','التخزين والحماية','الوصول إلى الرسائل محصور بالمسؤولين المخولين في لوحة الإدارة. يستخدم الموقع ملفات ارتباط ضرورية للجلسة وحماية النماذج؛ ولا يضيف أدوات تحليلات أو إعلانات. تُستخدم بصمة مشفرة لعنوان الاتصال لتحديد معدل الطلبات، وبصمة لمحتوى الرسالة لمنع التكرار؛ ولا يسجل التطبيق عنوان الاتصال الخام في قاعدة البيانات. قد تسجل خدمة الاستضافة بيانات وصول تقنية ضمن إعداداتها. يُحفظ اختيار النمط النهاري أو الليلي في متصفحك لتطبيقه عند عودتك، ولا يُرسل هذا الاختيار إلى الخادم. يمكنك تغيير الاختيار من زر النمط أو مسحه ضمن بيانات الموقع في متصفحك.'),section('rights','التواصل بشأن بياناتك','للاستفسار عن بياناتك أو طلب تصحيحها أو حذفها، راسل البريد الرسمي للشركة مع ذكر رقم الرسالة إن توفر. يمكن للمسؤول حذف الرسائل من لوحة الإدارة. تبقى الرسائل محفوظة إلى أن تُحذف، ولا توجد حالياً عملية حذف تلقائي.'),section('third','الملفات والروابط','تُحمّل الصور والخطوط والملف التعريفي من الموقع نفسه. لا تُحمّل خريطة أو خدمة خارجية تلقائياً. روابط الهاتف والبريد تفتح التطبيقات المناسبة على جهازك.')]
privacy_en=[section('collection','Information we collect','The contact form collects your name, email address and message. Company, phone number and sector are optional. We also store the message language, submission date, reference and follow-up status.'),section('use','How we use information','Contact information is used to respond to enquiries and follow up on business requests. This site does not use it for marketing campaigns. Requests are saved before receipt is confirmed. When email notifications are enabled, only the request reference and an admin link are emailed, without the message body.'),section('security','Storage and protection','Messages are accessible to authorised administrators. The site uses essential session and form-security cookies, with no analytics or advertising tools. A keyed hash of the connection address limits request frequency; a message fingerprint prevents duplicates. The application does not store the raw connection address in its database. The hosting service may keep technical access logs according to its configuration. Your light or dark mode preference is saved in your browser for future visits and is not sent to the server. You can change it using the theme button or remove it by clearing this site’s browser data.'),section('rights','Contact about your data','To ask about your data or request correction or deletion, contact the company’s official email and include your message reference if available. Administrators can delete messages. Messages remain stored until deleted, and no automatic deletion process currently runs.'),section('third','Files and external links','Images, fonts and the company profile are served by this site. No external map or service loads automatically. Phone and email links open the relevant apps on your device.')]
items.append(item('pages','privacy',tr('الخصوصية وبيانات التواصل','توضح هذه الصفحة البيانات التي يعالجها الموقع عند إرسال استفسار، وكيفية استخدامها وحمايتها.',{'eyebrow':'بياناتك','sections':privacy_ar},'Implemented functionality; retention policy pending','ar'),tr('Privacy & contact data','This page explains the information the site processes when you send an enquiry, how it is used and how it is protected.',{'eyebrow':'YOUR INFORMATION','sections':privacy_en},'Proposed translation; implemented functionality','en'),None,5))
items.append(item('pages','projects',tr('أعمالنا','تعرّف على المشاريع المنشورة ونطاق العمل في كل منها.',{'eyebrow':'المشاريع','sections':[]},'No project evidence in supplied PDF; hidden until approved project added','ar'),tr('Our work','Explore published projects and the scope of work for each.',{'eyebrow':'PROJECTS','sections':[]},'Proposed translation; no published projects','en'),None,6))
settings={'legal_name_ar':ar_name,'legal_name_en':en_name,'short_name_ar':'ارض اليرموك','short_name_en':'ARD ALYARMWK CO.','phone':'+964 780 144 4552','email':'info@ard-alyarmwk.com','address_ar':'العراق، بغداد، حي المتنبي\nمحلة 605، زقاق 2، مبنى 1، عمارة الزهراء','address_en':'Al-Mutanabbi district, Baghdad, Iraq\nDistrict 605, Alley 2, Building 1, Al-Zahraa Building','founded':'2017','whatsapp':'','map_url':'','social_links':[],'privacy_retention_note':'لم تعتمد مدة احتفاظ بعد؛ يلزم استكمالها قبل النشر.','translation_policy':'English content is a proposed translation pending company review; the legal name is verbatim from the cover.'}
media=[{'key':'architecture','file':'architecture-1280.webp','alt_ar':'واجهة مبنى زجاجي من زاوية معمارية — صورة توضيحية','alt_en':'Glass building façade from an architectural angle — illustrative image','source':'Unsplash https://images.unsplash.com/photo-1486406146926-c627a92ad1ab ; license https://unsplash.com/license','classification':'illustration'}, {'key':'energy','file':'energy-1280.webp','alt_ar':'ألواح طاقة شمسية في مساحة مفتوحة — صورة توضيحية','alt_en':'Solar panels in an open landscape — illustrative image','source':'Unsplash https://images.unsplash.com/photo-1509391366360-2e959784a276 ; license https://unsplash.com/license','classification':'illustration'}, {'key':'trade','file':'trade-1280.webp','alt_ar':'حاويات شحن تجارية — صورة توضيحية','alt_en':'Cargo shipping containers — illustrative image','source':'Unsplash https://images.unsplash.com/photo-1494412519320-aa613dfb7738 ; license https://unsplash.com/license','classification':'illustration'}, {'key':'industry','file':'industry-1280.webp','alt_ar':'أعمال تقنية في بيئة صناعية — صورة توضيحية','alt_en':'Technical work in an industrial setting — illustrative image','source':'Unsplash https://images.unsplash.com/photo-1581092921461-eab62e97a780 ; license https://unsplash.com/license','classification':'illustration'}]
for key,id,pg,ar,en in [('team',788,4,'تخطيط جماعي حول طاولة — صورة توضيحية من الملف التعريفي','Collaborative planning — illustration from the company profile'),('it',755,7,'مفهوم للبنية التقنية والبيانات — صورة توضيحية من الملف','Technology and data concept — illustration from the profile'),('software',756,8,'مفهوم للترابط الرقمي — صورة توضيحية من الملف','Digital connectivity concept — illustration from the profile')]:media.append(dict(key=key,file=key+'-1280.webp',alt_ar=ar,alt_en=en,source=f'User-provided PDF physical page {pg}, object {id}; supplied corporate reference, underlying stock license not provided.',classification='illustration'))
media.extend([dict(key='profile-cover',file='profile-cover.webp',alt_ar='غلاف الملف التعريفي الرسمي لشركة ارض اليرموك',alt_en='Official ARD ALYARMWK CO. profile cover',source='Original PDF physical page 1; rendered preview',classification='document'),dict(key='logo',file='logo.png',alt_ar='شعار ارض اليرموك',alt_en='ARD ALYARMWK CO. logo',source='Original user-provided logo.png, unmodified',classification='identity'),dict(key='profile',file='../company-profile.pdf',alt_ar='الملف التعريفي الرسمي',alt_en='Official company profile',source='Exact original user-supplied PDF, 10 pages',classification='document')])
# Use the visually reviewed current cover when the optional profile manifest is present.
profile_manifest=Path('database/profile-seed.json')
if profile_manifest.is_file():
 profile_data=json.loads(profile_manifest.read_text())
 for entry in media:
  if entry['key']=='profile-cover':
   entry.update(file=Path(profile_data['covers']['1280']['path']).name,alt_ar='الغلاف الأفقي للملف التعريفي الحالي لشركة ارض اليرموك',alt_en='Landscape cover of the current ARD ALYARMWK company profile',source=profile_data['source']+' Cover extracted from page 1.')
  if entry['key']=='profile':entry['source']=profile_data['source']
Path('database/seed.json').write_text(json.dumps(dict(settings=settings,media=media,items=items),ensure_ascii=False,indent=2))
