CREATE TABLE IF NOT EXISTS pages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(100) NOT NULL UNIQUE,
 sort_order INT NOT NULL DEFAULT 0,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 image_id BIGINT UNSIGNED NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS sectors LIKE pages;
CREATE TABLE IF NOT EXISTS projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(100) NOT NULL UNIQUE,
 sector_id BIGINT UNSIGNED NULL,
 sort_order INT NOT NULL DEFAULT 0,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 image_id BIGINT UNSIGNED NULL,
 gallery JSON NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS translations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 entity_type ENUM('pages','sectors','projects') NOT NULL,
 entity_id BIGINT UNSIGNED NOT NULL,
 locale ENUM('ar','en') NOT NULL,
 title VARCHAR(255) NOT NULL,
 summary TEXT NOT NULL,
 body JSON NOT NULL,
 seo_title VARCHAR(255) NOT NULL DEFAULT '',
 seo_description VARCHAR(500) NOT NULL DEFAULT '',
 status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 approval ENUM('review','approved') NOT NULL DEFAULT 'review',
 source_ref VARCHAR(255) NOT NULL DEFAULT '',
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY translation_key(entity_type,entity_id,locale)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS media (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 path VARCHAR(255) NOT NULL UNIQUE,
 original_name VARCHAR(255) NOT NULL,
 mime VARCHAR(100) NOT NULL,
 size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
 width INT NULL, height INT NULL,
 alt_ar VARCHAR(500) NOT NULL DEFAULT '', alt_en VARCHAR(500) NOT NULL DEFAULT '',
 source TEXT NOT NULL,
 classification ENUM('identity','illustration','project','document') NOT NULL DEFAULT 'illustration',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS settings (
 setting_key VARCHAR(100) PRIMARY KEY,
 value JSON NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS admins (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(254) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS contact_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reference CHAR(12) NOT NULL UNIQUE,
 locale ENUM('ar','en') NOT NULL,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL,
 company VARCHAR(150) NOT NULL DEFAULT '',
 phone VARCHAR(40) NOT NULL DEFAULT '',
 sector_slug VARCHAR(100) NOT NULL DEFAULT '',
 message TEXT NOT NULL,
 status ENUM('new','in_progress','closed') NOT NULL DEFAULT 'new',
 email_status ENUM('disabled','pending','sent','failed','logged') NOT NULL DEFAULT 'disabled',
 fingerprint CHAR(64) NOT NULL UNIQUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX inbox_index(status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 expires_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS audit_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 admin_id BIGINT UNSIGNED NULL,
 action VARCHAR(100) NOT NULL,
 entity VARCHAR(100) NOT NULL DEFAULT '',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
