<!doctype html><html lang="ar" dir="rtl"><head><?php require ROOT.'/app/views/theme-head.php';?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>لوحة الإدارة | ارض اليرموك</title><link rel="stylesheet" href="/assets/site.css"><script src="/assets/admin.js" defer></script><link rel="stylesheet" href="/assets/theme.css?v=<?=substr(hash_file('sha256',ROOT.'/public/assets/theme.css'),0,12)?>"><link rel="stylesheet" href="/assets/admin-sliders.css?v=<?=substr(hash_file('sha256',ROOT.'/public/assets/admin-sliders.css'),0,12)?>"></head><body><a class="skip-link" href="#admin-main">المحتوى</a><header class="admin-header"><?php require ROOT.'/app/views/theme-toggle.php';?><strong>ارض اليرموك / الإدارة</strong><a href="/admin">نظرة عامة</a><a href="/admin/list?type=pages">الصفحات</a><a href="/admin/list?type=sectors">القطاعات</a><a href="/admin/list?type=projects">المشاريع</a><a href="/admin/sliders" <?=in_array($adminRoute,['sliders','slider'],true)?'aria-current="page"':''?>>السلايدرات</a><a href="/admin/media">الوسائط</a><a href="/admin/settings">الإعدادات</a><a href="/admin/messages">الرسائل</a><a href="/admin/password">كلمة المرور</a><a href="/ar/" target="_blank" rel="noopener">عرض الموقع ↗</a><form method="post" action="/admin"><?=csrf_field()?><input type="hidden" name="action" value="logout"><button>خروج</button></form></header><main class="admin-wrap" id="admin-main"><?php if($adminError):?><div class="notice error" role="alert"><?=e($adminError)?> التغييرات لم تُحفظ.</div><?php endif;?><?php if($adminSuccess):?><div class="notice" role="status"><?=e($adminSuccess)?></div><?php endif;?><?php
if($adminRoute===''):
?><div class="admin-title"><div><p class="eyebrow">لوحة إدارة المحتوى</p><h1>مرحباً بك في ارض اليرموك.</h1><p>المحتوى الذي تحفظه هنا مرتبط مباشرة بالموقع.</p></div></div><div class="admin-grid"><?php foreach(['pages'=>'الصفحات','sectors'=>'القطاعات','projects'=>'المشاريع','media'=>'الوسائط','contact_messages'=>'رسائل التواصل'] as $table=>$label):?><a class="admin-stat" href="<?=in_array($table,['pages','sectors','projects'])?'/admin/list?type='.$table:($table==='media'?'/admin/media':'/admin/messages')?>"><b><?=query("SELECT COUNT(*) FROM $table")->fetchColumn()?></b><span><?=$label?></span></a><?php endforeach;?></div><div class="admin-card slider-dashboard-link"><div><h2>سلايدر مستقل لكل صفحة</h2><p>رتّب الصور والفيديو والنصوص للرئيسية ومن نحن والقطاعات وباقي الصفحات.</p></div><a class="button" href="/admin/sliders">إدارة السلايدرات ↗</a></div><div class="admin-card"><h2>قبل النشر العام</h2><p>المحتوى الإنكليزي ترجمة مقترحة للمراجعة؛ الاسم القانوني الإنكليزي من الغلاف الأصلي. اعتمد كل ترجمة بعد مراجعتها. المشاريع لا تظهر للزائر حتى نشر مشروع معتمد وصوره الحقيقية.</p><p>تحتاج مدة الاحتفاظ بالرسائل وحقوق الصور التوضيحية المضمنة في الملف الأصلي إلى مراجعة الشركة. لا يوجد رقم WhatsApp أو موقع خريطة موثق حالياً.</p><p>وضع الموقع: <strong><?=e(config('env'))?></strong> — البريد: <strong><?=e(config('mail_transport'))?></strong>. تغيير النطاق وSMTP من إعدادات الخادم خارج المجلد العام.</p></div><div class="admin-card"><h2>آخر التحديثات الإدارية</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>الإجراء</th><th>السجل</th><th>الوقت</th></tr></thead><tbody><?php foreach(query('SELECT * FROM audit_log ORDER BY id DESC LIMIT 10') as $a):?><tr><td><?=e($a['action'])?></td><td dir="ltr"><?=e($a['entity'])?></td><td dir="ltr"><?=e($a['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php elseif($adminRoute==='list'): $type=in_array(getstr('type'),['pages','sectors','projects'])?getstr('type'):'pages';$label=['pages'=>'الصفحات','sectors'=>'القطاعات','projects'=>'المشاريع'][$type];?><div class="admin-title"><div><h1><?=$label?></h1><p>تحرير المحتوى والترجمات وحالة النشر.</p></div><?php if($type!=='pages'):?><a class="button" href="/admin/edit?type=<?=$type?>">إضافة <?=$type==='sectors'?'قطاع':'مشروع'?> +</a><?php endif;?></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>العنوان</th><th>الرابط</th><th>الحالة</th><th>العربية</th><th>English</th></tr></thead><tbody><?php $contentRows=query("SELECT * FROM $type ORDER BY sort_order,id")->fetchAll();foreach($contentRows as $r):$trs=[];foreach(query('SELECT * FROM translations WHERE entity_type=? AND entity_id=?',[$type,$r['id']]) as $tr)$trs[$tr['locale']]=$tr;?><tr><td><?=e($trs['ar']['title']??$r['slug'])?></td><td dir="ltr"><?=e($r['slug'])?></td><td><span class="badge <?=e($r['status'])?>"><?=$r['status']==='published'?'منشور':'مسودة'?></span></td><?php foreach(['ar','en'] as $lc):?><td><a href="/admin/edit?type=<?=$type?>&id=<?=$r['id']?>&locale=<?=$lc?>">تحرير</a> <span class="badge <?=e($trs[$lc]['approval']??'review')?>"><?=($trs[$lc]['approval']??'')==='approved'?'معتمد':'للمراجعة'?></span></td><?php endforeach;?></tr><?php endforeach;if(!$contentRows):?><tr><td colspan="5">لا توجد مشاريع مدخلة. أضف البيانات والصور المعتمدة واحفظها كمسودة لحين اكتمال المراجعة.</td></tr><?php endif;?></tbody></table></div>
<?php elseif($adminRoute==='edit'):require ROOT.'/app/views/admin-editor.php';
elseif($adminRoute==='sliders'):require ROOT.'/app/views/admin-sliders.php';
elseif($adminRoute==='slider'):require ROOT.'/app/views/admin-slider-editor.php';
elseif($adminRoute==='settings'):require ROOT.'/app/views/admin-settings.php';
elseif($adminRoute==='media'||$adminRoute==='media-edit'):require ROOT.'/app/views/admin-media.php';
elseif($adminRoute==='messages'||$adminRoute==='message'):require ROOT.'/app/views/admin-messages.php';
elseif($adminRoute==='password'):?><div class="admin-title"><h1>تغيير كلمة المرور</h1></div><form method="post" class="admin-card"><?=csrf_field()?><input type="hidden" name="action" value="change-password"><?php foreach(['current_password'=>'كلمة المرور الحالية','new_password'=>'كلمة المرور الجديدة (12 حرفاً على الأقل)','confirm_password'=>'تأكيد كلمة المرور الجديدة'] as $key=>$label):?><div class="field"><label for="<?=$key?>"><?=$label?></label><input id="<?=$key?>" type="password" name="<?=$key?>" required maxlength="200" autocomplete="<?=$key==='current_password'?'current-password':'new-password'?>" dir="ltr"></div><?php endforeach;?><button class="button">تحديث كلمة المرور</button></form>
<?php else:?><h1>الصفحة الإدارية غير موجودة</h1><a class="text-link" href="/admin">لوحة الإدارة</a><?php endif;?></main></body></html>
