<?php
$type=in_array(getstr('type'),['pages','sectors','projects'])?getstr('type'):'pages';$id=(int)getstr('id');$locale=in_array(getstr('locale'),['ar','en'])?getstr('locale'):'ar';
$entity=$id?query("SELECT * FROM $type WHERE id=?",[$id])->fetch():['id'=>0,'slug'=>'','status'=>'draft','sort_order'=>0,'image_id'=>null,'sector_id'=>null,'gallery'=>'[]'];
if(!$entity){echo '<div class="notice error">المحتوى غير موجود.</div>';return;}
$translation=$id?query('SELECT * FROM translations WHERE entity_type=? AND entity_id=? AND locale=?',[$type,$id,$locale])->fetch():false;
$tr=$translation?:['title'=>'','summary'=>'','body'=>'{"sections":[]}','seo_title'=>'','seo_description'=>'','status'=>'draft','approval'=>'review','source_ref'=>''];$body=json_decode($tr['body'],true);
if(!$translation&&$id){$base=query('SELECT body FROM translations WHERE entity_type=? AND entity_id=? LIMIT 1',[$type,$id])->fetchColumn();if($base){$body=json_decode($base,true);foreach($body['sections']??[] as &$section){$section['title']='';$section['text']='';$section['items']=[];}unset($section);$body['slider']=[];$body['eyebrow']='';$body['services']=[];$body['text']='';}}
require_once ROOT.'/app/admin-form-helpers.php';
$mediaOptions=[''=>'بدون صورة'];foreach(query("SELECT id,original_name FROM media WHERE mime LIKE 'image/%' ORDER BY id DESC") as $m)$mediaOptions[$m['id']]='#'.$m['id'].' — '.$m['original_name'];
$previewPath=$type==='pages'?($entity['slug']==='home'?'':$entity['slug']):$type.'/'.$entity['slug'];
?><div class="admin-title"><div><h1><?=$id?'تحرير المحتوى':'إضافة '.($type==='sectors'?'قطاع':'مشروع')?></h1><p><?=e($entity['slug'])?> / <?=$locale==='ar'?'العربية':'English'?></p></div><a class="text-link" href="/admin/list?type=<?=$type?>">العودة للقائمة</a></div>
<?php if($id):?><nav class="admin-tabs" aria-label="لغة المحتوى"><?php foreach(['ar'=>'العربية','en'=>'English'] as $lc=>$label):?><a href="/admin/edit?type=<?=$type?>&id=<?=$id?>&locale=<?=$lc?>" <?=$locale===$lc?'aria-current="page"':''?>><?=$label?></a><?php endforeach;?></nav><?php endif;?>
<form method="post" class="admin-editor" data-unsaved><?=csrf_field()?><input type="hidden" name="action" value="save-content"><input type="hidden" name="type" value="<?=$type?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="locale" value="<?=$locale?>">
<div class="admin-card"><h2>إعدادات المحتوى</h2><div class="form-grid"><?php afield('slug','الرابط الثابت',$entity['slug'],false,'ltr',($type==='pages'?'readonly ':'').'required maxlength="100"');afield('sort_order','ترتيب الظهور',$entity['sort_order'],false,'ltr','type="number" min="0" max="1000"');aselect('status','حالة السجل',['draft'=>'مسودة','published'=>'منشور'],$entity['status']);aselect('translation_status','حالة هذه اللغة',['draft'=>'مسودة','published'=>'منشورة'],$tr['status']);aselect('approval','اعتماد هذه اللغة',['review'=>'ترجمة / نص مقترح للمراجعة','approved'=>'معتمد للنشر'],$tr['approval']);aselect('image_id','الصورة الرئيسية',$mediaOptions,$entity['image_id']);?></div><p class="admin-hint">يمكن معاينة المسودات بعد الحفظ. في إعداد الإنتاج الافتراضي لا تظهر الترجمة حتى تصبح منشورة ومعتمدة. اختر من مكتبة الوسائط، أو ارفع صورة جديدة هناك أولاً.</p></div>
<div class="admin-card"><h2>النصوص — <?=$locale==='ar'?'العربية':'English'?></h2><?php $direction=$locale==='ar'?'rtl':'ltr';afield('eyebrow','العبارة التمهيدية',$body['eyebrow']??'',false,$direction,'maxlength="255"');afield('title','العنوان الرئيسي — يمكن استخدام سطرين',$tr['title'],true,$direction,'required maxlength="255"');afield('summary','المقدمة المختصرة',$tr['summary'],true,$direction,'maxlength="4000"');if($type!=='pages'):afield('services','نطاق الخدمات — عنصر واحد في كل سطر',implode("\n",$body['services']??[]),true,$direction);afield('text','تفاصيل إضافية — تفصل الفقرات بسطر فارغ',$body['text']??'',true,$direction);else:?><input type="hidden" name="services" value=""><input type="hidden" name="text" value="<?=e($body['text']??'')?>"><?php endif;afield('source_ref','المصدر الداخلي / مرجع موافقة النشر',$tr['source_ref'],true,'ltr','maxlength="255"');?><p class="admin-hint">مرجع المصدر يظهر في الإدارة فقط. لا تحول نشاطاً مسجلاً إلى مشروع منجز دون دليل.</p></div>
<?php if($type==='projects'):?><div class="admin-card"><h2>بيانات المشروع المعتمدة</h2><?php $sectorOptions=[''=>'اختر القطاع'];foreach(records('sectors','ar',true) as $sector)$sectorOptions[$sector['id']]=$sector['title'];aselect('sector_id','قطاع المشروع',$sectorOptions,$entity['sector_id']??null);foreach(['location'=>'الموقع','scope'=>'نطاق العمل','completion_status'=>'الحالة (مثلاً قيد التنفيذ، بعد الاعتماد)','client'=>'الجهة المستفيدة المسموح بنشرها'] as $key=>$label)afield($key,$label,$body[$key]??'',false,$direction);?><p class="admin-hint">تظهر الحقول المكتملة فقط. نشر المشروع يتطلب صورة مصنفة «مشروع حقيقي» ومصدر اعتماد وقطاعاً.</p><h3>معرض الصور</h3><div class="gallery-checks"><?php $gallery=json_decode($entity['gallery']??'[]',true)??[];foreach(query("SELECT * FROM media WHERE mime LIKE 'image/%' AND classification='project'") as $m):?><label><?=picture((int)$m['id'])?><input type="checkbox" name="gallery[]" value="<?=$m['id']?>" <?=in_array((int)$m['id'],$gallery,true)?'checked':''?>><?=e($m['original_name'])?></label><?php endforeach;?></div></div><?php endif;?>
<?php if($body['sections']??[]):?><div class="admin-card admin-sections"><h2>أقسام الصفحة وترتيبها</h2><p class="admin-hint">عدّل عناوين الأقسام ونصوصها. تغيير رقم الترتيب يعيد ترتيب الأقسام في الصفحة. إزالة علامة الظهور تخفي القسم.</p><?php $sectionList=$body['sections'];if($adminError&&is_array($_POST['sections']??null))$sectionList=$_POST['sections'];foreach($sectionList as $i=>$s):$prefix='sections['.$i.']';$items=is_string($s['items']??null)?$s['items']:implode("\n",array_map(fn($v)=>$v['title'].' | '.$v['text'],$s['items']??[]));?><details><summary><?=e($s['title']?:$s['key'])?></summary><input type="hidden" name="<?=$prefix?>[key]" value="<?=e($s['key'])?>"><div class="form-grid"><div class="field"><label for="section-order-<?=$i?>">الترتيب</label><input id="section-order-<?=$i?>" name="<?=$prefix?>[order]" type="number" min="0" max="1000" value="<?=e($s['order']??0)?>"></div><div class="field"><label for="section-visible-<?=$i?>">ظهور القسم</label><select id="section-visible-<?=$i?>" name="<?=$prefix?>[visible]"><option value="1" <?=($s['visible']??false)?'selected':''?>>ظاهر</option><option value="0" <?=!($s['visible']??false)?'selected':''?>>مخفي</option></select></div></div><div class="field"><label for="section-title-<?=$i?>">العنوان</label><textarea id="section-title-<?=$i?>" name="<?=$prefix?>[title]" rows="2" dir="<?=$direction?>"><?=e($s['title'])?></textarea></div><div class="field"><label for="section-text-<?=$i?>">النص</label><textarea id="section-text-<?=$i?>" name="<?=$prefix?>[text]" rows="4" dir="<?=$direction?>"><?=e($s['text']??'')?></textarea></div><div class="field"><label for="section-items-<?=$i?>">القائمة — كل سطر: عنوان | وصف</label><textarea id="section-items-<?=$i?>" name="<?=$prefix?>[items]" rows="5" dir="<?=$direction?>"><?=e($items)?></textarea></div></details><?php endforeach;?></div><?php endif;?>
<?php require ROOT.'/app/views/admin-slider.php';?>
<div class="admin-card"><h2>محركات البحث والمشاركة</h2><?php afield('seo_title','عنوان الصفحة لمحركات البحث',$tr['seo_title'],false,$direction,'maxlength="255"');afield('seo_description','وصف الصفحة لمحركات البحث',$tr['seo_description'],true,$direction,'maxlength="500"');?><p class="admin-hint">تستخدم بيانات الصفحة نفسها في Open Graph. النطاق الرئيسي من إعداد base_url على الخادم.</p></div><div class="admin-actions sticky"><button class="button" type="submit">حفظ التغييرات</button><?php if($id):?><a class="button button-outline" target="_blank" rel="noopener" href="<?=url($previewPath,$locale)?>?preview=1">معاينة النسخة المحفوظة ↗</a><?php endif;?><span class="admin-hint">الحفظ يحدث لغة واحدة وإعدادات السجل المشتركة.</span></div></form>
