<section class="container inner-hero contact-hero split-heading"><div><p class="eyebrow"><?=e($row['body']['eyebrow']??'')?></p><h1><?=nl2br(e($row['title']))?></h1></div><p class="large-copy"><?=e($row['summary'])?></p></section>
<div class="container contact-layout"><aside class="contact-details" aria-label="<?=t('بيانات الاتصال الرسمية','Official contact details')?>"><div class="contact-detail"><span><?=t('اتصل بنا','CALL US')?></span><a class="ltr" href="tel:<?=e(preg_replace('/\s/','',setting('phone')))?>"><?=e(setting('phone'))?></a></div><div class="contact-detail"><span><?=t('راسلنا','EMAIL US')?></span><a class="ltr" href="mailto:<?=e(setting('email'))?>"><?=e(setting('email'))?></a></div><div class="contact-detail"><span><?=t('مقر الشركة','OUR ADDRESS')?></span><p><?=nl2br(e(setting('address_'.lang())))?></p><?php if(setting('map_url')):?><a class="text-link" href="<?=e(setting('map_url'))?>" target="_blank" rel="noopener"><?=t('الموقع على الخريطة','View on map')?> ↗</a><?php endif;?></div><?php if(setting('whatsapp')):?><div class="contact-detail"><a href="https://wa.me/<?=e(preg_replace('/\D/','',setting('whatsapp')))?>" target="_blank" rel="noopener">WhatsApp ↗</a></div><?php endif;?><p class="contact-aside-note"><?=t('للاستفسارات المؤسسية، فرص التعاون ومتطلبات المشاريع، يسعدنا استقبال رسالتك.','For business enquiries, collaboration opportunities and project requirements, we welcome your message.')?></p><?php foreach(setting('social_links',[]) as $social):?><a class="text-link" href="<?=e($social['url'])?>" target="_blank" rel="noopener"><?=e($social['label'])?> ↗</a><?php endforeach;?><?php page_slider($row,'pages','contact','contact',false);?></aside>
<div id="contact-form">
<?php if(getstr('received')==='1'&&!empty($_SESSION['contact_receipt'])):?><div class="notice" role="status"><strong><?=t('تم استلام رسالتك بنجاح.','Your message has been received.')?></strong><p><?=t('حُفظ طلبك للمتابعة. الرقم المرجعي:','Your request is saved for follow-up. Reference:')?> <bdi><?=e($_SESSION['contact_receipt'])?></bdi></p></div><?php unset($_SESSION['contact_receipt']);endif;?>
<?php if($errors):?><div class="notice error" role="alert" tabindex="-1"><strong><?=t('تعذر إرسال الرسالة. راجع ما يلي:','Your message could not be sent. Please check:')?></strong><ul><?php foreach($errors as $k=>$error):?><li><?php if($k!=='form'):?><a href="#field-<?=e($k)?>"><?=e($error)?></a><?php else:echo e($error);endif;?></li><?php endforeach;?></ul></div><?php endif;?>
<form class="contact-form" method="post" action="<?=url('contact')?>#contact-form" data-submit-once>
<h2><?=t('ناقش مشروعك معنا','Discuss your project')?></h2><p class="form-intro"><?=t('الحقول المشار إليها بـ * مطلوبة.','Fields marked * are required.')?></p><?=csrf_field()?>
<div class="hp" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
<div class="form-grid">
<?php foreach(['name'=>[t('الاسم الكامل','Full name'),'text',true,100,'name'],'email'=>[t('البريد الإلكتروني','Email address'),'email',true,254,'email'],'company'=>[t('الشركة / الجهة','Company / organisation'),'text',false,150,'organization'],'phone'=>[t('رقم الهاتف','Phone number'),'tel',false,40,'tel']] as $key=>[$label,$fieldtype,$required,$max,$autocomplete]):?><div class="field"><label for="field-<?=$key?>"><?=$label?> <?=$required?'*':'<span class="optional">'.t('(اختياري)','(optional)').'</span>'?></label><input id="field-<?=$key?>" name="<?=$key?>" type="<?=$fieldtype?>" autocomplete="<?=$autocomplete?>" maxlength="<?=$max?>" <?= $required?'required':'' ?> <?=$key==='name'?'minlength="2"':''?> value="<?=e($old[$key]??'')?>" <?=in_array($key,['email','phone'])?'dir="ltr"':''?> <?=isset($errors[$key])?'aria-invalid="true" aria-describedby="error-'.$key.'"':''?>><?php if(isset($errors[$key])):?><span class="field-error" id="error-<?=$key?>"><?=e($errors[$key])?></span><?php endif;?></div><?php endforeach;?>
<div class="field full"><label for="field-sector"><?=t('القطاع محل الاهتمام','Sector of interest')?> <span class="optional"><?=t('(اختياري)','(optional)')?></span></label><select id="field-sector" name="sector" <?=isset($errors['sector'])?'aria-invalid="true" aria-describedby="error-sector"':''?>><option value=""><?=t('اختر القطاع المناسب','Choose a relevant sector')?></option><?php foreach($sectors as $sector):?><option value="<?=e($sector['slug'])?>" <?=($old['sector']??getstr('sector'))===$sector['slug']?'selected':''?>><?=e($sector['title'])?></option><?php endforeach;?></select><?php if(isset($errors['sector'])):?><span class="field-error" id="error-sector"><?=e($errors['sector'])?></span><?php endif;?></div>
<div class="field full"><label for="field-message"><?=t('حدثنا عن احتياجاتك','Tell us what you need')?> *</label><textarea id="field-message" name="message" rows="5" minlength="15" maxlength="5000" required <?=isset($errors['message'])?'aria-invalid="true" aria-describedby="error-message"':''?>><?=e($old['message']??'')?></textarea><?php if(isset($errors['message'])):?><span class="field-error" id="error-message"><?=e($errors['message'])?></span><?php endif;?></div></div><p class="form-policy"><?=t('تُستخدم بياناتك لمتابعة استفسارك وفق','Your information is used to follow up on your enquiry under our')?> <a href="<?=url('privacy')?>"><?=t('سياسة الخصوصية.','privacy policy.')?></a></p><button class="button" type="submit"><?=t('أرسل رسالتك','Send your message')?><span class="arrow" aria-hidden="true">↗</span></button></form></div></div>
