<section class="hero container"><div class="hero-copy"><p class="eyebrow"><span></span><?=e($row['body']['eyebrow']??'')?></p><h1><?=nl2br(e($row['title']))?></h1><p class="hero-description"><?=e($row['summary'])?></p><div class="button-row"><a class="button" href="<?=url('contact')?>"><?=t('ناقش مشروعك معنا','Discuss your project')?><span class="arrow" aria-hidden="true">↗</span></a><a class="text-link" href="<?=e(media_url((int)setting('profile_id')))?>" target="_blank" rel="noopener"><?=t('عرض الملف التعريفي','View company profile')?><span aria-hidden="true">↗</span><span class="sr-only"><?=t(' — يفتح PDF في نافذة جديدة',' — opens PDF in a new tab')?></span></a></div><div class="hero-footnote"><span class="tiny-mark" aria-hidden="true"><i></i><i></i><i></i></span><span><?=t('من أرض العراق، نحو آفاق أوسع.','From Iraq, towards wider horizons.')?></span></div></div><div class="hero-visual"><?php page_slider($row,'pages','home','hero');?></div></section>
<div class="sector-ribbon"><div class="container"><span><?=t('مجالاتنا','OUR FIELDS')?></span><p><?=t('مقاولات وتجارة','Contracting & trade')?></p><i></i><p><?=t('تقنية واتصالات','Technology & communications')?></p><i></i><p><?=t('طاقة وصناعة','Energy & industry')?></p><a href="<?=url('sectors')?>"><?=t('اكتشف المزيد','Explore more')?> <span class="arrow" aria-hidden="true">↗</span></a></div></div>
<?php foreach(sections($row) as $section):extract(['s'=>$section]);switch($s['key']):case 'about':?>
<section class="section container intro-section"><div><p class="eyebrow"><?=t('01 / تعرّف على ارض اليرموك','01 / MEET ARD ALYARMWK')?></p><h2><?=nl2br(e($s['title']))?></h2></div><div class="intro-copy"><p class="large-copy"><?=e($s['text'])?></p><div class="intro-bottom"><a class="text-link" href="<?=url('about')?>"><?=t('تعرّف على الشركة','Get to know us')?> <span class="arrow" aria-hidden="true">↗</span></a><span class="since"><b dir="ltr"><?=e(setting('founded'))?></b><span><?=t('سنة التأسيس','ESTABLISHED')?></span></span></div></div></section>
<?php break;case 'sectors':?>
<section class="section sectors-feature"><div class="container"><div class="section-heading"><div><p class="eyebrow"><?=t('02 / قطاعاتنا','02 / OUR SECTORS')?></p><h2><?=nl2br(e($s['title']))?></h2></div><p><?=e($s['text'])?></p></div><div class="sector-explorer"><div class="sector-list">
<?php foreach($sectors as $i=>$sector):?><div class="sector-option <?=$i===0?'active':''?>"><span class="sector-number" dir="ltr"><?=sprintf('%02d',$i+1)?></span><a href="<?=url('sectors/'.$sector['slug'])?>"><?=e($sector['title'])?></a><button type="button" class="sector-select" data-sector="<?=$i?>" aria-pressed="<?=$i===0?'true':'false'?>" aria-controls="sector-panel-<?=$i?>" aria-label="<?=e(t('معاينة قطاع ','Preview ').$sector['title'])?>"><span aria-hidden="true">↗</span></button></div><?php endforeach;?></div><div class="sector-panels"><?php foreach($sectors as $i=>$sector):?><article class="sector-panel" id="sector-panel-<?=$i?>" <?=$i?'hidden':''?>><?=picture((int)$sector['image_id'],'sector-image')?><div class="sector-panel-copy"><span class="sector-panel-index" dir="ltr"><?=sprintf('%02d',$i+1)?> / 08</span><h3><?=e($sector['title'])?></h3><p><?=e($sector['summary'])?></p><a class="text-link" href="<?=url('sectors/'.$sector['slug'])?>"><?=t('استكشف هذا القطاع','Explore this sector')?> <span class="arrow" aria-hidden="true">↗</span></a></div></article><?php endforeach;?><p class="image-note"><?=t('الصور توضيحية لمجالات العمل.','Images illustrate our fields of work.')?></p></div></div></div></section>
<?php break;case 'approach':?>
<section class="section container approach"><div class="approach-title"><p class="eyebrow"><?=t('03 / ما يوجه أعمالنا','03 / WHAT GUIDES US')?></p><h2><?=nl2br(e($s['title']))?></h2><p><?=e($s['text'])?></p><div class="architectural-mark" aria-hidden="true"><i></i><i></i><i></i></div></div><div class="principle-list"><?php foreach($s['items'] as $i=>$v):?><article><span dir="ltr"><?=sprintf('%02d',$i+1)?></span><div><h3><?=e($v['title'])?></h3><p><?=e($v['text'])?></p></div><span class="principle-plus" aria-hidden="true">+</span></article><?php endforeach;?></div></section>
<?php break;case 'profile':require ROOT.'/app/views/profile-banner.php';break;case 'cta':require ROOT.'/app/views/cta.php';break;endswitch;endforeach;?>
<?php if($projects):?><section class="section container"><div class="section-heading"><h2><?=t('مشاريع مختارة','Selected projects')?></h2><a class="text-link" href="<?=url('projects')?>"><?=t('جميع المشاريع','All projects')?> ↗</a></div><?php $listedProjects=array_slice($projects,0,3);require ROOT.'/app/views/project-grid.php';?></section><?php endif;?>
