<?php $video=$slide['video'];$videoId=$sliderId.'-video-'.$i;$videoDescription=($video['desktop']['alt_'.lang()]?:t('فيلم ارض اليرموك','ARD ALYARMWK company film')).' '.t('الفيديو صامت.','This video has no audio.');?>
<div class="showcase-video-screen" data-video-screen>
<?=picture((int)$slide['image_id'],'showcase-video-poster',($priority&&$i===0),'')?>
<video id="<?=$videoId?>" class="showcase-film" data-showcase-video data-video-desktop="<?=e(video_url((int)$video['desktop']['id'],$video['version']))?>" data-video-mobile="<?=e(video_url((int)$video['mobile']['id'],$video['version']))?>" muted playsinline preload="none" width="1280" height="720" aria-label="<?=e(t('فيلم ارض اليرموك','ARD ALYARMWK company film'))?>" aria-describedby="<?=$videoId?>-description" tabindex="-1" hidden></video>
<progress class="showcase-video-progress" data-video-progress value="0" max="<?=e($video['duration']?:1)?>" aria-hidden="true"></progress>
</div>
<div class="showcase-copy showcase-video-caption"><div class="showcase-video-text"><p class="showcase-tag"><?=e($slide['tag'])?> <span class="showcase-video-duration" dir="ltr"><?=sprintf('%02d:%02d',floor($video['duration']/60),ceil($video['duration'])%60)?></span></p><h2><?=e($slide['title'])?></h2><?php if($slide['text']):?><p class="showcase-description"><?=e($slide['text'])?></p><?php endif;?><p class="showcase-video-note"><?=t('مشاهد توضيحية','Illustrative footage')?></p><?php if($slide['href']):?><a class="showcase-link" href="<?=e($slide['href'])?>"><?=t('اكتشف المزيد','Explore more')?> <span class="arrow" aria-hidden="true">↗</span></a><?php endif;?></div>
<button type="button" class="showcase-video-toggle" data-video-toggle aria-controls="<?=$videoId?>" aria-label="<?=t('تشغيل الفيديو','Play video')?>" data-play-label="<?=t('تشغيل الفيديو','Play video')?>" data-pause-label="<?=t('إيقاف الفيديو مؤقتاً','Pause video')?>" hidden><svg data-video-play-icon viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="m9 5 11 7-11 7z"/></svg><svg data-video-pause-icon viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" hidden><path d="M7 5h3v14H7zm7 0h3v14h-3z"/></svg></button>
<noscript><a class="showcase-link showcase-film-fallback" href="<?=e(video_viewer_url((int)$video['id']))?>" target="_blank" rel="noopener"><?=t('شاهد الفيديو','Watch the film')?> ↗</a></noscript></div>
<p class="sr-only" id="<?=$videoId?>-description"><?=e($videoDescription)?></p>
<p class="showcase-video-error" data-video-error role="status" hidden><?=t('تعذر تشغيل الفيديو.','The video could not be played.')?> <a href="<?=e(video_viewer_url((int)$video['id']))?>" target="_blank" rel="noopener"><?=t('افتح الفيديو مباشرة','Open the video directly')?> ↗</a></p>
